version: '3'

services:

  database:
    image: postgres
    container_name: essayb-database-dev
    environment:
      POSTGRES_DB: ESSAYB_DEV
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
    ports:
      - 5432:5432

  backend:
    image: essayb:backend-dev
    container_name: essayb-backend-dev
    build:
      context: backend
      dockerfile: Dockerfile.dev
    environment:
      DEPLOY_DEBUG: "true"
      DEPLOY_RELOAD: "true"
      DATABASE_URI: 'postgres://root:toor@database/ESSAYB_DEV'
    volumes:
      - ./backend/api:/code/api
      - ./backend/logs:/code/logs
      - ./backend/setup.py:/code/setup.py
    ports:
      - 8888:8888

  frontend:
    image: essayb:frontend-dev
    container_name: essayb-frontend-dev
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/code/src/
      - ./frontend/public:/code/public/
      - ./frontend/config:/code/config/
      - ./frontend/package.json:/code/package.json
      - ./frontend/package-lock.json:/code/package-lock.json
    ports:
      - 8080:8080
