version: '3'

services:

  database:
    image: postgres
    container_name: essayb-database-dev
    environment:
      POSTGRES_DB: ESSAYB_DEV
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
    ports:
      - 5432:5432

  backend:
    image: essayb:backend-dev
    container_name: essayb-backend-dev
    build:
      context: backend
      dockerfile: Dockerfile.dev
    environment:
      DEPLOY_DEBUG: "true"
      DEPLOY_RELOAD: "true"
      DATABASE_URI: 'postgres://root:toor@database/ESSAYB_DEV'
    volumes:
      - ./backend/api:/code/api
      - ./backend/logs:/code/logs
      - ./backend/setup.py:/code/setup.py
    depends_on:
      - database

  frontend:
    image: essayb:frontend-dev
    container_name: essayb-frontend-dev
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    environment:
      BACKEND_DOMAIN: 0.0.0.0:8080
      USE_HTTPS: 0
    volumes:
      - ./frontend/next.config.js:/code/next.config.js
      - ./frontend/src:/code/src/
      - ./frontend/public:/code/public/
      - ./frontend/config:/code/config/
      - ./frontend/package.json:/code/package.json
      - ./frontend/package-lock.json:/code/package-lock.json
    depends_on:
      - database

  gateway:
    image: essayb:gateway-dev
    container_name: essayb-gateway-dev
    build:
      context: gateway
      dockerfile: Dockerfile.dev
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - backend
      - frontend
      - database
    logging:
      driver: none